objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Acknowledgement_Email_Template__c</fullName>
        <description>Text: the name of the primary email template used for acknowledging donations related to this campaign.</description>
        <inlineHelpText>The name of the primary email template used for acknowledging donations related to this campaign.</inlineHelpText>
        <label>Acknowledgement Email Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Acknowledgement_Template_Id__c</fullName>
        <description>Id: text field set by trigger to the GUID of the email template specified in Acknowledgement_Email_Template. This field should only be edited by SFDC and not an end user.</description>
        <label>Acknowledgement_Template_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestCampaignTrigger.cls
@isTest
private class TestCampaignTrigger {
	
	@isTest static void test_insert() {
		EmailTemplate x = [Select Id,Name From EmailTemplate Where DeveloperName = 'Annual_Fund_Thank_You'];
		Campaign c = new Campaign(Name='TestCampaign', Acknowledgement_Email_Template__c ='Annual Fund Thank You');
		test.startTest();
		insert c;
		test.stopTest();
		
		// there's a more elegant way to do this?
		Campaign r = [Select Id,Acknowledgement_Template_Id__c,Name from Campaign Where Name = 'TestCampaign'];
		System.assertEquals(r.Acknowledgement_Template_Id__c,x.Id);
	}
}